
# SEO settings
title: "David Lichtenberg"
title2: "" # default: ""
description: "Just another minimalist Jekyll theme that focuses on technical writing."
keywords: "Machine Learning, AI, artificial intelligence, deep learning, python, software, software development, programming, web, data, big data"
url: http://dmlicht.github.io # site url
baseurl: null # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://github.com/dmlicht/dmlicht.github.io
disqus_shortname: "dmlicht"
twitter_username: "dmlicht"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "David Lichtenberg"
  job      : "Machine Learning Software Engineer"
  bio      : ""
  thumb    : /images/author.jpg
  email    : dlicht91@gmail.com
  url      : http://dmlicht.github.io
  github   : http://github.com/dmlicht
  twitter  : http://twitter.com/dmlicht
  facebook : ""
  linkedin : ""

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@dmlicht"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
